import { StoreFooter, StoreHeader } from "@/components/StoreHeader";
import { useCart } from "@/contexts/CartContext";
import { formatMoney, salePercent } from "@/lib/money";
import { trpc } from "@/lib/trpc";
import { motion, useScroll, useTransform } from "framer-motion";
import { ArrowDownRight, ArrowUpRight, ChevronRight, Loader2, Plus } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { Link } from "wouter";

const HERO_TEXTURE = "/manus-storage/libass-kinetic-fabric-hero_e3ba0419.jpg";
const LOOKBOOK: { image: string; title: string; note: string }[] = [];

export default function Home() {
  const { data: products = [], isLoading } = trpc.commerce.products.list.useQuery({ first: 8 }, { refetchInterval: 20000 });
  const { data: uploaded = [] } = trpc.brand.lookbook.useQuery(undefined, { refetchInterval: 20000 });
  const { data: motionFrames = [] } = trpc.brand.motion.useQuery(undefined, { refetchInterval: 20000 });
  const { data: homeSections = [] } = trpc.brand.homeSections.useQuery(undefined, { refetchInterval: 20000 });
  const featured = products.slice(0, 4);
  const frames = [...LOOKBOOK, ...uploaded.map(image => ({ image: image.imageUrl, title: image.title, note: "Studio upload" }))];
  return <div className="kinetic-shell min-h-screen overflow-x-hidden"><CinematicIntroduction /><StoreHeader /><main>
    <Hero />
    <section className="border-y border-white/15 bg-[#d4ff00] px-5 py-3 text-[#121212]"><div className="mx-auto flex max-w-7xl items-center justify-between gap-4 font-mono text-[9px] tracking-[.15em] uppercase"><span>Libaas by HAYA / Drop 04</span><span className="hidden sm:block">Cash on Delivery only</span><span>Engineered for movement</span></div></section>
    <section id="shop" className="bg-[#121212] px-5 py-18 sm:px-8 sm:py-24"><div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-6 border-b border-white/15 pb-7 sm:flex-row sm:items-end"><div><p className="eyebrow">Current motion / 04</p><h2 className="mt-3 max-w-xl font-display text-5xl leading-[.86] sm:text-7xl">FORM IS<br /><span className="text-white/35">A FREQUENCY.</span></h2></div><Link href="/shop" className="magnetic-button inline-flex w-fit items-center gap-2 border border-white/30 px-4 py-3 font-mono text-[10px] tracking-[.14em] text-white uppercase"><span>Explore all</span><ArrowUpRight className="h-3.5 w-3.5" /></Link></div><div className="mt-8">{isLoading ? <div className="flex min-h-64 items-center justify-center"><Loader2 className="h-5 w-5 animate-spin text-[#d4ff00]" /></div> : featured.length ? <div className="grid grid-cols-2 gap-x-3 gap-y-10 sm:grid-cols-4 sm:gap-x-5">{featured.map(product => <KineticProduct key={product.id} product={product} />)}</div> : <FallbackGrid />}</div></div></section>
    <GarmentScrub frames={motionFrames} />
    <section id="lookbook" className="border-y border-white/15 bg-[#181818] py-18 sm:py-24"><div className="mx-auto max-w-7xl px-5 sm:px-8"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="eyebrow">Archive / scroll study</p><h2 className="mt-3 font-display text-5xl leading-[.86] sm:text-7xl">THE BODY<br /><span className="text-white/35">IN MOTION.</span></h2></div><p className="max-w-xs font-mono text-[10px] leading-5 tracking-[.08em] text-white/45 uppercase">Scroll horizontally through the complete garment record. Every frame, every fold, every angle.</p></div><div className="mt-10 flex snap-x snap-mandatory gap-4 overflow-x-auto scroll-smooth pb-5 [-ms-overflow-style:none] [scrollbar-width:none] [&::-webkit-scrollbar]:hidden">{frames.map((frame, index) => <motion.article initial={{ opacity: 0, y: 22 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: .1 }} transition={{ delay: index * .06, duration: .45 }} key={`${frame.image}-${index}`} className="group relative w-[77vw] max-w-[430px] shrink-0 snap-start overflow-hidden border border-white/15 bg-white/5"><div className="aspect-[.72] overflow-hidden"><img src={frame.image} alt={frame.title} className="h-full w-full object-cover transition duration-700 group-hover:scale-[1.04]" /></div><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-[#121212] via-[#121212]/55 to-transparent p-5 pt-22"><p className="font-mono text-[9px] tracking-[.16em] text-[#d4ff00] uppercase">{frame.note}</p><h3 className="mt-2 font-display text-3xl">{frame.title}</h3></div></motion.article>)}</div><p className="mt-1 inline-flex items-center gap-2 font-mono text-[9px] tracking-[.14em] text-white/45 uppercase"><ChevronRight className="h-3.5 w-3.5 text-[#d4ff00]" />Scroll right to expose every view</p></div></section>
    {homeSections.filter(section => section.items.length > 0).map(section => <CustomHomeSection key={section.id} section={section} />)}
    <TechBlock />
    <section className="kinetic-grid border-t border-white/15 bg-[#121212] px-5 py-20 sm:px-8 sm:py-28"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[1.15fr_.85fr] lg:items-end"><div><p className="eyebrow">The Libaas code</p><h2 className="mt-3 max-w-3xl font-display text-6xl leading-[.84] sm:text-8xl">QUIET<br /><span className="text-[#d4ff00]">MOVES</span><br />LOUD.</h2></div><div><p className="max-w-md text-base leading-8 text-white/65">Libaas by HAYA is modern modest fashion built around proportion, texture, and a confidence that doesn't need to ask for attention.</p><Link href="/shop" className="magnetic-button mt-8 inline-flex items-center gap-3 border border-white/30 px-5 py-3 font-mono text-[10px] tracking-[.15em] text-white uppercase"><span>Explore drop 04</span><ArrowUpRight className="h-3.5 w-3.5" /></Link></div></div></section>
  </main><StoreFooter /></div>;
}

function CinematicIntroduction() { const [open, setOpen] = useState(true); const enter = () => setOpen(false); if (!open) return null; return <motion.section role="dialog" aria-modal="true" aria-labelledby="libaas-intro-title" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="fixed inset-0 z-[80] overflow-hidden bg-[#171417] text-[#f8f4ea]"><motion.img initial={{ scale: 1.08, opacity: .45 }} animate={{ scale: 1, opacity: .75 }} transition={{ duration: 5.5, ease: "easeOut" }} src={HERO_TEXTURE} alt="" className="absolute inset-0 h-full w-full object-cover" /><div className="absolute inset-0 bg-[radial-gradient(circle_at_72%_42%,rgba(225,194,122,.18),transparent_27%),linear-gradient(90deg,rgba(23,20,23,.98),rgba(23,20,23,.8)_48%,rgba(23,20,23,.32))]" /><div className="relative mx-auto flex min-h-full max-w-6xl flex-col justify-between px-6 py-7 sm:px-10 sm:py-10"><div className="flex items-center justify-between font-mono text-[9px] tracking-[.18em] text-[#e1c27a] uppercase"><span>Libaas by HAYA</span><span>01 / Introduction</span></div><div className="max-w-2xl"><motion.p initial={{ opacity: 0, y: 14 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .45, duration: .8 }} className="font-mono text-[10px] tracking-[.18em] text-[#e1c27a] uppercase">Modern modest dress / considered slowly</motion.p><motion.h1 id="libaas-intro-title" initial={{ opacity: 0, y: 24 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .8, duration: .9 }} className="mt-5 font-display text-[clamp(3.2rem,8vw,6.8rem)] leading-[.88]">A quieter study<br /><span className="text-white/55">in form & fabric.</span></motion.h1><motion.p initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: 1.35, duration: .9 }} className="mt-7 max-w-md text-sm leading-7 text-white/70">A house collection built around proportion, texture, and pieces that move with composure. Explore every garment angle, then order with Cash on Delivery.</motion.p></div><motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 1.75, duration: .7 }} className="flex flex-wrap items-center justify-between gap-5"><button autoFocus onClick={enter} className="inline-flex items-center gap-3 bg-[#e1c27a] px-5 py-3 font-mono text-[10px] tracking-[.16em] text-[#171417] uppercase transition hover:bg-white focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-white">Enter the collection <ArrowUpRight className="h-3.5 w-3.5" /></button><p className="font-mono text-[9px] tracking-[.14em] text-white/45 uppercase">Fabric · silhouette · delivery</p></motion.div></div></motion.section>; }
function Hero() { return <section className="relative min-h-[calc(84vh-70px)] overflow-hidden bg-[#171417]"><motion.div initial={{ scale: 1.035 }} animate={{ scale: 1 }} transition={{ duration: 14, ease: "linear", repeat: Infinity, repeatType: "reverse" }} className="absolute inset-0"><img src={HERO_TEXTURE} alt="Macro fabric texture in motion" className="h-full w-full object-cover opacity-70" /></motion.div><div className="absolute inset-0 bg-[radial-gradient(circle_at_75%_40%,rgba(225,194,122,.13),transparent_25%),linear-gradient(90deg,rgba(23,20,23,.98)_0%,rgba(23,20,23,.68)_48%,rgba(23,20,23,.12)_100%)]" /><div className="relative mx-auto flex min-h-[calc(84vh-70px)] max-w-7xl items-end px-5 pb-12 pt-28 sm:px-8 sm:pb-18 lg:items-center"><div className="max-w-2xl"><p className="kinetic-reveal font-mono text-[10px] tracking-[.17em] text-[#e1c27a] uppercase">Libaas by HAYA / Drop 04</p><h1 className="kinetic-reveal-delay mt-5 font-display text-[clamp(3.5rem,7vw,6.8rem)] leading-[.82] tracking-[-.06em]">FORM,<br /><span className="text-white/42">CONSIDERED.</span></h1><p className="kinetic-reveal-delay-2 mt-6 max-w-lg text-sm leading-7 text-white/65">Modern modest pieces built in texture, balance, and a measured sense of occasion.</p><div className="kinetic-reveal-delay-2 mt-8 flex flex-wrap items-center gap-4"><Link href="/shop" className="magnetic-button inline-flex items-center gap-3 border border-[#e1c27a] bg-[#e1c27a] px-5 py-3 font-mono text-[10px] tracking-[.15em] text-[#171417] uppercase"><span>Explore the collection</span><ArrowUpRight className="h-3.5 w-3.5" /></Link><a href="#lookbook" className="inline-flex items-center gap-2 px-3 py-3 font-mono text-[10px] tracking-[.15em] text-white/75 uppercase hover:text-[#e1c27a]"><ArrowDownRight className="h-4 w-4" />View garment stories</a></div></div></div><div className="absolute bottom-5 right-5 hidden font-mono text-[9px] tracking-[.14em] text-white/45 uppercase sm:block">01 / Macro textile study</div></section>; }

function CustomHomeSection({ section }: { section: { title: string; items: { id: number; title: string; imageUrl: string; altText: string | null; linkProductHandle: string | null }[] } }) {
  return <section className="border-y border-white/15 bg-[#121212] py-16 sm:py-22"><div className="mx-auto max-w-7xl px-5 sm:px-8"><div className="flex items-end justify-between gap-4"><h2 className="font-display text-4xl leading-[.9] sm:text-6xl">{section.title}</h2></div><div className="mt-8 flex snap-x snap-mandatory gap-4 overflow-x-auto scroll-smooth pb-4 [-ms-overflow-style:none] [scrollbar-width:none] [&::-webkit-scrollbar]:hidden">{section.items.map(item => { const card = <div className="group relative w-[46vw] max-w-[280px] shrink-0 snap-start overflow-hidden border border-white/15 bg-white/5"><div className="aspect-[.76] overflow-hidden"><img src={item.imageUrl} alt={item.altText ?? item.title} className="h-full w-full object-cover transition duration-700 group-hover:scale-[1.04]" /></div>{item.title && <p className="p-3 text-sm">{item.title}</p>}</div>; return item.linkProductHandle ? <Link key={item.id} href={`/products/${item.linkProductHandle}`}>{card}</Link> : <div key={item.id}>{card}</div>; })}</div></div></section>;
}

function KineticProduct({ product }: { product: any }) { const { addItem, loading } = useCart(); const variant = product.variants[0]; const image = product.images[0]; const discount = variant ? salePercent(variant.price, variant.compareAtPrice) : null; return <article className="kinetic-card group"><Link href={`/products/${product.handle}`} className="relative block overflow-hidden border border-white/15 bg-white/5"><div className="aspect-[.76] overflow-hidden">{image && <img src={image.url} alt={image.altText ?? product.title} className="kinetic-card-media h-full w-full object-cover transition duration-700" />}</div>{discount && <span className="absolute left-2 top-2 bg-[#d4ff00] px-2 py-1 font-mono text-[8px] tracking-[.1em] text-[#121212] uppercase">-{discount}%</span>}</Link><div className="mt-3 flex items-start justify-between gap-3"><div><p className="text-sm font-medium">{product.title}</p><div className="mt-1 flex gap-2 font-mono text-[10px] text-white/55">{variant?.compareAtPrice && <span className="line-through">{formatMoney(variant.compareAtPrice)}</span>}<span className={discount ? "text-[#d4ff00]" : ""}>{variant && formatMoney(variant.price)}</span></div></div><button onClick={() => variant && addItem(variant.id, 1)} disabled={!variant?.availableForSale || loading} className="quick-add shrink-0 border border-[#d4ff00] p-2 text-[#d4ff00] hover:bg-[#d4ff00] hover:text-[#121212]" aria-label={`Quick add ${product.title}`}><Plus className="h-3.5 w-3.5" /></button></div></article>; }
function FallbackGrid() { return <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{LOOKBOOK.concat(LOOKBOOK).slice(0, 4).map((frame, index) => <div key={index}><div className="aspect-[.76] overflow-hidden border border-white/15"><img src={frame.image} alt={frame.title} className="h-full w-full object-cover grayscale transition hover:grayscale-0" /></div><p className="mt-3 text-sm">{frame.title}</p><p className="mt-1 font-mono text-[9px] text-white/45 uppercase">Coming soon</p></div>)}</div>; }
function GarmentScrub({ frames }: { frames: Array<{ id: number; title: string; imageUrl: string; altText: string | null }> }) { const ref = useRef<HTMLDivElement>(null); const { scrollYProgress } = useScroll({ target: ref, offset: ["start end", "end start"] }); const rotate = useTransform(scrollYProgress, [0, .5, 1], [-14, 0, 13]); const scale = useTransform(scrollYProgress, [0, .5, 1], [.82, 1.04, .86]); const y = useTransform(scrollYProgress, [0, 1], [120, -100]); const fallback = { title: "Three-piece suit", imageUrl: "/manus-storage/libass-azure-garden-three-piece-front_d0597b75.png", altText: "Three-piece garment motion study" }; const sequence = frames.length ? frames.slice(0, 6) : [fallback]; const [activeFrame, setActiveFrame] = useState(0); useEffect(() => { setActiveFrame(0); return scrollYProgress.on("change", progress => { setActiveFrame(Math.min(sequence.length - 1, Math.max(0, Math.floor(progress * sequence.length)))); }); }, [scrollYProgress, sequence.length]); const frame = sequence[activeFrame] ?? sequence[0]; return <section ref={ref} className="relative min-h-[115vh] overflow-hidden border-y border-white/15 bg-[#d4ff00] text-[#121212]"><div className="sticky top-0 flex min-h-screen items-center px-5 py-16 sm:px-8"><div className="mx-auto grid w-full max-w-7xl gap-9 lg:grid-cols-[.9fr_1.1fr] lg:items-center"><div><p className="font-mono text-[10px] tracking-[.16em] uppercase">Scroll-driven garment study</p><h2 className="mt-4 font-display text-6xl leading-[.82] tracking-[-.09em] sm:text-8xl">CUT TO<br />MOVE.</h2><p className="mt-7 max-w-sm text-sm leading-7 text-[#121212]/70">A scroll-scrubbed silhouette study that responds to your journey through the collection. Studio can now control every motion frame separately from suit galleries.</p><div className="mt-8 flex gap-5 font-mono text-[9px] tracking-[.14em] uppercase"><span>01 / Drape</span><span>02 / Pace</span><span>03 / Form</span></div></div><div className="relative flex min-h-[450px] items-center justify-center sm:min-h-[620px]"><motion.div style={{ rotate, scale, y }} className="relative h-[68vh] max-h-[680px] w-[78%] max-w-[480px] overflow-hidden border border-[#121212]/20 bg-[#121212]"><img key={frame.imageUrl} src={frame.imageUrl} alt={frame.altText ?? frame.title} className="h-full w-full object-cover" /><div className="absolute inset-x-0 bottom-0 border-t border-white/20 bg-[#121212]/80 px-4 py-3 font-mono text-[9px] tracking-[.14em] text-white uppercase">{frame.title} / frame {activeFrame + 1} of {sequence.length}</div></motion.div><div className="absolute right-[3%] top-[10%] h-22 w-22 border border-[#121212]/25" /><div className="absolute bottom-[7%] left-[3%] h-16 w-16 rounded-full border border-[#121212]/30" /></div></div></div></section>; }
function TechBlock() { return <section className="bg-[#121212] px-5 py-20 sm:px-8 sm:py-28"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[.8fr_1.2fr]"><div className="lg:sticky lg:top-28 lg:h-fit"><p className="eyebrow">Material dialogue</p><h2 className="mt-3 font-display text-6xl leading-[.84] sm:text-7xl">DESIGNED<br />TO <span className="text-[#d4ff00]">BREATHE.</span></h2><p className="mt-7 max-w-sm text-sm leading-7 text-white/55">A closer view of the decisions behind a garment. Technical specifications are always listed on the product page when available.</p></div><div className="divide-y divide-white/15 border-y border-white/15">{[["01", "Soft structure", "Fluid construction that makes room for the body to move."], ["02", "Kinetic fit", "Proportion-led cutting, considered for a calm and composed silhouette."], ["03", "Textile record", "Each collection image is archived in full, from front profile to finishing detail."]].map(([number, title, copy]) => <article key={number} className="grid gap-4 py-8 sm:grid-cols-[90px_1fr]"><span className="font-mono text-[10px] tracking-[.14em] text-[#d4ff00]">{number}</span><div><h3 className="font-display text-4xl tracking-[-.06em]">{title}</h3><p className="mt-3 max-w-md text-sm leading-6 text-white/55">{copy}</p></div></article>)}</div></div></section>; }
