import { StoreFooter, StoreHeader } from "@/components/StoreHeader";
import { useCart } from "@/contexts/CartContext";
import { formatMoney, salePercent } from "@/lib/money";
import { trpc } from "@/lib/trpc";
import { ArrowUpRight, Loader2, Plus, SlidersHorizontal } from "lucide-react";
import { useMemo, useState } from "react";
import { Link } from "wouter";

export default function Shop() { const { data: products = [], isLoading } = trpc.commerce.products.list.useQuery({ first: 48 }); const { data: collections = [] } = trpc.commerce.collections.list.useQuery({ first: 20 }); const [active, setActive] = useState<string | null>(null); const filtered = useMemo(() => active ? products.filter(product => product.tags.some(tag => tag.toLowerCase() === active.toLowerCase()) || (product.productType ?? "").toLowerCase() === active.toLowerCase()) : products, [active, products]); return <div className="min-h-screen bg-[#121212] text-white"><StoreHeader /><main><section className="kinetic-grid border-b border-white/15 px-5 py-14 sm:px-8 sm:py-20"><div className="mx-auto max-w-7xl"><p className="eyebrow">Archive / all objects</p><div className="mt-4 flex flex-col justify-between gap-7 md:flex-row md:items-end"><h1 className="max-w-3xl font-display text-6xl leading-[.82] sm:text-8xl">FORM,<br /><span className="text-white/35">CATALOGUED.</span></h1><p className="max-w-xs text-sm leading-7 text-white/55">Objects for a considered wardrobe. Full garment stories, regular-and-sale pricing, and Cash on Delivery checkout.</p></div></div></section><section className="mx-auto max-w-7xl px-5 pt-7 sm:px-8"><div className="flex flex-wrap items-center gap-2 border-b border-white/15 pb-6"><span className="mr-3 inline-flex items-center gap-2 font-mono text-[9px] tracking-[.14em] text-white/45 uppercase"><SlidersHorizontal className="h-3.5 w-3.5 text-[#d4ff00]" />Filter archive</span><Filter active={!active} onClick={() => setActive(null)}>All objects</Filter>{collections.map(collection => <Filter key={collection.id} active={active === collection.title} onClick={() => setActive(active === collection.title ? null : collection.title)}>{collection.title}</Filter>)}</div></section><section className="mx-auto max-w-7xl px-5 pb-24 pt-8 sm:px-8">{isLoading ? <div className="flex min-h-72 items-center justify-center"><Loader2 className="h-5 w-5 animate-spin text-[#d4ff00]" /></div> : filtered.length ? <div className="grid grid-cols-2 gap-x-3 gap-y-10 sm:grid-cols-3 sm:gap-x-5 lg:grid-cols-4">{filtered.map(product => <CatalogCard key={product.id} product={product} />)}</div> : <div className="flex min-h-72 flex-col items-center justify-center text-center"><p className="font-display text-5xl">Archive in motion.</p><p className="mt-3 text-sm text-white/55">Try another filter as the next drop is being organized.</p></div>}</section></main><StoreFooter /></div>; }
function Filter({ active, onClick, children }: { active: boolean; onClick: () => void; children: string }) { return <button onClick={onClick} className={`border px-3 py-2 font-mono text-[9px] tracking-[.11em] uppercase transition ${active ? "border-[#d4ff00] bg-[#d4ff00] text-[#121212]" : "border-white/20 text-white/65 hover:border-white"}`}>{children}</button>; }
function CatalogCard({ product }: { product: any }) { const { addItem, loading } = useCart(); const variant = product.variants[0]; const image = product.images[0]; const discount = variant ? salePercent(variant.price, variant.compareAtPrice) : null; return <article className="kinetic-card group"><Link href={`/products/${product.handle}`} className="relative block overflow-hidden border border-white/15 bg-white/5"><div className="aspect-[.78] overflow-hidden">{image && <img src={image.url} alt={image.altText ?? product.title} className="kinetic-card-media h-full w-full object-cover transition duration-700" />}</div>{discount && <span className="absolute left-2 top-2 bg-[#d4ff00] px-2 py-1 font-mono text-[8px] tracking-[.1em] text-[#121212] uppercase">-{discount}%</span>}<span className="absolute right-2 top-2 font-mono text-[8px] tracking-[.1em] text-white/60 uppercase">{product.productType || "Object"}</span></Link><div className="mt-3 flex gap-2"><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{product.title}</p><div className="mt-1 flex gap-2 font-mono text-[10px] text-white/50">{variant?.compareAtPrice && <span className="line-through">{formatMoney(variant.compareAtPrice)}</span>}<span className={discount ? "text-[#d4ff00]" : ""}>{variant && formatMoney(variant.price)}</span></div></div><button onClick={() => variant && addItem(variant.id, 1)} disabled={loading || !variant?.availableForSale} className="quick-add border border-[#d4ff00] p-2 text-[#d4ff00] hover:bg-[#d4ff00] hover:text-[#121212]" aria-label={`Quick add ${product.title}`}><Plus className="h-3.5 w-3.5" /></button></div><Link href={`/products/${product.handle}`} className="mt-3 inline-flex items-center gap-1 font-mono text-[9px] tracking-[.12em] text-white/45 uppercase hover:text-[#d4ff00]">View object <ArrowUpRight className="h-3 w-3" /></Link></article>; }
