import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { useStudioPanelRoot } from "@/components/useStudioPanelRoot";
import { Check, Loader2, MessageCircle, X } from "lucide-react";
import { createPortal } from "react-dom";
import { toast } from "sonner";

export function ReviewManager({ adminToken }: { adminToken: string }) {
  const utils = trpc.useUtils();
  const { data: reviews = [], isLoading } = trpc.admin.reviews.list.useQuery({ adminToken, limit: 1000 });
  const update = trpc.admin.reviews.updateStatus.useMutation({ onSuccess: async () => { await utils.admin.reviews.list.invalidate(); toast.success("Review moderation status saved."); }, onError: error => toast.error(error.message) });
  const studioMain = useStudioPanelRoot();
  if (!studioMain) return null;
  return createPortal(<section className="mt-10 border border-white/15 bg-[#181818] p-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="eyebrow">Customer reviews</p><h2 className="mt-2 font-display text-4xl">Verified notes only</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-white/55">Reviews are created only after the order number, email, and purchased item are matched. Nothing is invented or published automatically.</p></div><MessageCircle className="h-6 w-6 text-[#e1c27a]" /></div><div className="mt-7 divide-y divide-white/10 border-t border-white/10">{isLoading ? <div className="p-7 text-center"><Loader2 className="mx-auto h-4 w-4 animate-spin text-[#e1c27a]" /></div> : reviews.length ? reviews.map(review => <article key={review.id} className="grid gap-4 py-5 lg:grid-cols-[1fr_auto]"><div><div className="flex flex-wrap items-center gap-3"><p className="text-sm font-medium">{review.customerName}</p><span className="font-mono text-[9px] tracking-[.12em] text-[#e1c27a] uppercase">{review.rating} / 5 stars</span><span className={`font-mono text-[9px] tracking-[.12em] uppercase ${review.status === "published" ? "text-emerald-300" : review.status === "rejected" ? "text-red-300" : "text-white/45"}`}>{review.status}</span></div><p className="mt-2 text-sm leading-6 text-white/65">{review.body}</p><p className="mt-2 font-mono text-[9px] text-white/40">{review.productHandle} · {review.orderNumber}</p></div><div className="flex flex-wrap gap-2 self-start"><Button type="button" disabled={update.isPending || review.status === "published"} onClick={() => update.mutate({ adminToken, id: review.id, status: "published" })} className="h-9 rounded-none bg-[#e1c27a] px-3 font-mono text-[9px] tracking-[.12em] text-[#171417] uppercase hover:bg-white"><Check className="h-3.5 w-3.5" />Publish</Button><Button type="button" variant="outline" disabled={update.isPending || review.status === "rejected"} onClick={() => update.mutate({ adminToken, id: review.id, status: "rejected" })} className="h-9 rounded-none border-red-300/45 px-3 font-mono text-[9px] tracking-[.12em] text-red-200 uppercase hover:bg-red-300 hover:text-[#171417]"><X className="h-3.5 w-3.5" />Reject</Button></div></article>) : <p className="py-8 text-sm text-white/45">No order-verified review submissions yet.</p>}</div></section>, studioMain);
}
